services:
  # Main application container with frontend, backend, and nginx
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    volumes:
      - ./logs:/var/log/supervisor
    environment:
      - NODE_ENV=production
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

